var data_color = [
  {
    name: '#FFFFFF',
    css: 'var(--color-dark)',
    class_color: 'text-dark',
    class_bg: 'bg-dark',
    description: 'สี dark ที่ใช้ใน <span class="text-danger"> theme dark </span>จะไม่ค่อยใช้ bg-white หรือ text-white ',
    color_text: '#000000',
  },
  {
    name: '#3E88FB',
    css: 'var(--color-primary)',
    class_color: 'text-primary',
    class_bg: 'bg-primary',
    description: 'สี primary ใช้กับพวกปุ่มยืนยัน',
    color_text: '#FFFFFF',
  },
  {
    name: '#58606E',
    css: 'var(--color-secondary)',
    class_color: 'text-secondary',
    class_bg: 'bg-secondary',
    description: 'สี secondary ส่วนมากจะใช้เป็นสีตัวอักษรตัวลอง ที่ใช้ใน <span class="text-danger"> theme white</span>',
    color_text: '#FFFFFF',
  },
  {
    name: '#0BAA22',
    css: 'var(--color-success)',
    class_color: 'text-success',
    class_bg: 'bg-success',
    description: 'สี success ที่ใช้ใน <span class="text-danger"> theme white</span>',
    color_text: '#FFFFFF',
  },
  {
    name: '#3A4248',
    css: 'var(--color-info)',
    class_color: 'text-info',
    class_bg: 'bg-info',
    description: 'สี info ส่วนมากจะใช้เป็นสีตัวอักษรตัวหลัก ที่ใช้ใน <span class="text-danger"> theme white</span> <br><span class="text-danger"">ถ้าใช้เป็น css </span>ถ้าเป็น <span class="text-danger"> theme dark </span>สี BG ของ Nav bar ด้านบน Card และสีรอง <br> สามารถใช้เป็นสีของ hover ใน table',
    color_text: '#FFFFFF',
  },
  {
    name: '#FFBD3A',
    css: 'var(--color-warning)',
    class_color: 'text-warning',
    class_bg: 'bg-warning',
    description: 'ไม่ค่อยได้ใช้นะ',
    color_text: '#000000',
  },
  {
    name: '#FE635B',
    css: 'var(--color-danger)',
    class_color: 'text-danger',
    class_bg: 'bg-danger',
    description: 'สี danger ใช้เน่นคำหรืออะไรที่ error',
    color_text: '#FFFFFF',
  },
  {
    name: '#E6E6E6',
    css: 'var(--bg-card-navbar)',
    class_color: 'text-light',
    class_bg: 'bg-light',
    description: 'สี light ที่ใช้ใน <span class="text-danger"> theme white</span> ส่วนมากจะให้เป็นสีของปุ่ม ยกเลิก <br><span class="text-danger"">ถ้าใช้เป็น css </span> สี BG ของ Nav bar ด้านบน Card และสีรอง <br> สามารถใช้เป็นสีของ hover ใน table',
    color_text: '#9CA2A8',
  },
  {
    name: '#000000',
    css: 'var(--color-dark)',
    class_color: 'text-dark',
    class_bg: 'bg-dark',
    description: 'สี dark ที่ใช้ใน <span class="text-danger"> theme white</span> ไม่ค่อยได้ใช้นะ',
    color_text: '#FFFFFF',
  },
  {
    name: '#EEEEED',
    css: 'var(--bg-color)',
    class_color: '',
    class_bg: '',
    description: 'ใช้เป็นสี background-color ของ <span class="text-danger"> theme white</span> หลัก',
    color_text: '#000000',
  },
  {
    name: '#FBFBFB',
    css: 'var(--bg-card)',
    class_color: '',
    class_bg: '',
    description: 'สีหลักของ Card ของ <span class="text-danger"> theme white</span> กับสี bg table',
    color_text: '#000000',
  },
  {
    name: '#DADEE3',
    css: 'var(--bg-card-back)',
    class_color: '',
    class_bg: '',
    description: 'ใช้เป็นสี BG ของแถบ Pagination หรือ Back หรือ Stroke / Border  ที่ใช้ใน <span class="text-danger"> theme white</span>',
    color_text: '#000000',
  },
  {
    name: '#D5D5D5',
    css: 'var(--bg-card-optional-1)',
    class_color: '',
    class_bg: '',
    description: 'เอาไว้ตัดกับสีหลักเพื่อแยกเนื้อหา ที่ใช้ใน <span class="text-danger"> theme white</span>',
    color_text: '#000000',
  },
  {
    name: '#DEDEDE',
    css: 'var(--bg-card-optional-2)',
    class_color: '',
    class_bg: '',
    description: 'เอาไว้ตัดกับสีหลักเพื่อแยกเนื้อหา ที่ใช้ใน <span class="text-danger"> theme white</span>',
    color_text: '#000000',
  },
  {
    name: '#D0D6DD',
    css: 'var(--color-field)',
    class_color: '',
    class_bg: '',
    description: 'ใช้เป็นสีของเส้นใน INPUT ที่ใช้ใน <span class="text-danger"> theme white</span>',
    color_text: '#000000',
  },
  {
    name: '#5C9CFF',
    css: 'var(--color-field-active)',
    class_color: '',
    class_bg: '',
    description: 'ใช้เป็นสีของเส้นใน INPUT ตอนที่ Active หรือ Focus ที่ใช้ใน <span class="text-danger"> theme white</span>',
    color_text: '#000000',
  },
  {
    name: '#A5AABE',
    css: 'var(--color-secondary)',
    class_color: 'text-secondary',
    class_bg: 'bg-secondary',
    description: 'สี secondary ส่วนมากจะใช้เป็นสีตัวอักษรตัวลอง ที่ใช้ใน <span class="text-danger"> theme dark </span>',
    color_text: '#000000',
  },
  {
    name: '#31C947',
    css: 'var(--color-success)',
    class_color: 'text-success',
    class_bg: 'bg-success',
    description: 'สี success ที่ใช้ใน <span class="text-danger"> theme dark</span >',
    color_text: '#000000',
  },
  {
    name: '#DADBE0',
    css: 'var(--color-info)',
    class_color: 'text-info',
    class_bg: 'bg-info',
    description: 'สี info ส่วนมากจะใช้เป็นสีตัวอักษรตัวหลัก ที่ใช้ใน <span class="text-danger"> theme dark</span >',
    color_text: '#000000',
  },
  {
    name: '#232B32',
    css: 'var(--bg-color)',
    class_color: '',
    class_bg: '',
    description: 'ใช้เป็นสี background-color ของ <span class="text-danger"> theme dark</span> ',
    color_text: '#FFFFFF',
  },
  {
    name: '#2E373D',
    css: 'var(--bg-card)',
    class_color: '',
    class_bg: '',
    description: 'สีหลักของ Card ของ <span class="text-danger"> theme dark </span>กับสี bg table',
    color_text: '#FFFFFF',
  },
  {
    name: '#2A3238',
    css: 'var(--bg-card-back)',
    class_color: '',
    class_bg: '',
    description: 'ใช้เป็นสี BG ของแถบ Pagination หรือ Back หรือ Stroke / Border  ที่ใช้ใน <span class="text-danger"> theme dark</span >',
    color_text: '#FFFFFF',
  },
  {
    name: '#1B2126',
    css: 'var(--bg-card-optional-1)',
    class_color: '',
    class_bg: '',
    description: 'เอาไว้ตัดกับสีหลักเพื่อแยกเนื้อหา ที่ใช้ใน <span class="text-danger"> theme dark</span >',
    color_text: '#FFFFFF',
  },
  {
    name: '#282E33',
    css: 'var(--bg-card-optional-2)',
    class_color: '',
    class_bg: '',
    description: 'เอาไว้ตัดกับสีหลักเพื่อแยกเนื้อหา ที่ใช้ใน <span class="text-danger"> theme dark</span >',
    color_text: '#FFFFFF',
  },
  {
    name: '#454C52',
    css: 'var(--color-field)',
    class_color: '',
    class_bg: '',
    description: 'ใช้เป็นสีของเส้นใน INPUT ที่ใช้ใน <span class="text-danger"> theme dark</span >',
    color_text: '#FFFFFF',
  },
  {
    name: '#89B3F7',
    css: 'var(--color-field-active)',
    class_color: '',
    class_bg: '',
    description: 'ใช้เป็นสีของเส้นใน INPUT ตอนที่ Active หรือ Focus ที่ใช้ใน <span class="text-danger"> theme dark</span >',
    color_text: '#000000',
  },
  {
    name: '#9CA2A8',
    css: 'var(--color-place-holder)',
    class_color: '',
    class_bg: '',
    description: 'สีของ Place Holder ที่ใช้ใน <span class="text-danger"> theme dark</span >',
    color_text: '#000000',
  },
  {
    name: '#778396',
    css: 'var(--color-place-holder)',
    class_color: '',
    class_bg: '',
    description: 'สีของ Place Holder',
    color_text: '#000000',
  },
  {
    name: '#F7F7F7',
    css: 'var(--color-table)',
    class_color: '',
    class_bg: '',
    description: 'สีของ table ที่ใช้ใน <span class="text-danger"> theme white</span >',
    color_text: '#000000',
  },
  {
    name: '#3A4248',
    css: 'var(--color-table)',
    class_color: '',
    class_bg: '',
    description: 'สีของ table ที่ใช้ใน <span class="text-danger"> theme dark</span >',
    color_text: '#ffffff',
  },
  {
    name: '#F5F5F5',
    css: 'var(--bg-hover-optional-1)',
    class_color: '',
    class_bg: '',
    description: 'เอาไว้สี hover ที่ใช้ใน <span class="text-danger"> theme white</span>',
    color_text: '#000000',
  },
  {
    name: '#EAEAEA',
    css: 'var(--bg-hover-optional-2)',
    class_color: '',
    class_bg: '',
    description: 'เอาไว้สี hover ที่ใช้ใน <span class="text-danger"> theme white</span>',
    color_text: '#000000',
  },
  {
    name: '#1B2126',
    css: 'var(--bg-hover-optional-1)',
    class_color: '',
    class_bg: '',
    description: 'เอาไว้สี hover ที่ใช้ใน <span class="text-danger"> theme white</span>',
    color_text: '#ffffff',
  },
  {
    name: '#1B2126',
    css: 'var(--bg-hover-optional-2)',
    class_color: '',
    class_bg: '',
    description: 'เอาไว้สี hover ที่ใช้ใน <span class="text-danger"> theme white</span>',
    color_text: '#ffffff',
  },
  {
    name: '#F2F2F2',
    css: 'var(--color-sub-table)',
    class_color: '',
    class_bg: '',
    description: '',
    color_text: '#ffffff',
  },
  {
    name: '#DAE7FB',
    css: 'var(--color-active-table)',
    class_color: '',
    class_bg: '',
    description: 'เอาไว้สี active ที่ใช้ใน table',
    color_text: '#ffffff',
  },
  {
    name: '#ffffff',
    css: 'var(--color-dark-or-light)',
    class_color: '',
    class_bg: '',
    description: 'theme white',
    color_text: '#ffffff',
  },
  {
    name: '#000000',
    css: 'var(--color-dark-or-light)',
    class_color: '',
    class_bg: '',
    description: 'dark white',
    color_text: '#000000',
  },
];